In [81]:
import torch
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [80]:
input1 = torch.rand(100,128,128)
input2 = torch.rand(100,128,128)
cos = torch.nn.CosineSimilarity()
output = cos(input1, input2)
output

tensor([[0.7428, 0.7686, 0.7276,  ..., 0.7105, 0.7253, 0.7546],
        [0.7325, 0.7754, 0.7859,  ..., 0.7542, 0.7317, 0.7539],
        [0.6830, 0.7138, 0.7625,  ..., 0.7496, 0.7239, 0.7552],
        ...,
        [0.7795, 0.7601, 0.7606,  ..., 0.7118, 0.7656, 0.7530],
        [0.7508, 0.7619, 0.7568,  ..., 0.7649, 0.7349, 0.7900],
        [0.7718, 0.7475, 0.7207,  ..., 0.7440, 0.7347, 0.7051]])

In [93]:
news = pd.read_csv('news.csv')

vectorizer = TfidfVectorizer(stop_words='english')
tfidf_train = vectorizer.fit_transform(news['text'])

In [94]:
tfidf_tensor = torch.Tensor(tfidf_train.todense())
# print(tfidf_train.size)
# print(tfidf_tensor.size())
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
output = cosine_similarity(tfidf_tensor,tfidf_tensor)

In [83]:
print(tfidf_tensor[:2])
print(type(tfidf_train))
print(output)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
<class 'scipy.sparse.csr.csr_matrix'>
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.0224036  0.         0.02263735]
 [0.         0.         1.0000001  ... 0.         0.         0.        ]
 ...
 [0.         0.0224036  0.         ... 1.0000002  0.         0.02972867]
 [0.         0.         0.         ... 0.         1.0000001  0.        ]
 [0.         0.02263735 0.         ... 0.02972867 0.         1.        ]]


In [100]:
similar = list(enumerate(output[0]))
similar = sorted(similar, key=lambda x: x[1], reverse=True)
similar = similar[1:6]
movie_index = [i[0] for i in similar]
titles = news['title'].iloc[movie_index]

print(f"News article looking at: {news['title'].iloc[0]}")
print("Recomendations:")
for text in titles:
    print(text)

News article looking at: You Can Smell Hillary’s Fear
Recomendations:
FBI REDUX: What’s Behind New Probe into Hillary Clinton Emails?
Memo to Comey: Keep Your Damn Hands Off Our Elections
FBI “Insurrection” to Scuttle Director, Rig Election
Clinton Camp Tries to Deflect Suspicion as FBI Reopens Email Case
NBC's Baghdad Bob: There Is No FBI Investigation of Hillary | Frontpage Mag
