In [19]:
import torch
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import time

In [2]:
input1 = torch.rand(100,128,128)
input2 = torch.rand(100,128,128)
cos = torch.nn.CosineSimilarity()
output = cos(input1, input2)
output

tensor([[0.7640, 0.7270, 0.7637,  ..., 0.7466, 0.7765, 0.7504],
        [0.7426, 0.6588, 0.7067,  ..., 0.7216, 0.7315, 0.8110],
        [0.6645, 0.7823, 0.7544,  ..., 0.7043, 0.7350, 0.7656],
        ...,
        [0.7635, 0.7249, 0.7209,  ..., 0.7516, 0.7072, 0.7501],
        [0.7687, 0.7753, 0.8053,  ..., 0.7512, 0.7266, 0.7726],
        [0.7559, 0.7432, 0.7128,  ..., 0.7469, 0.7006, 0.7218]])

In [3]:
news = pd.read_csv('news.csv')

vectorizer = TfidfVectorizer(stop_words='english')
tfidf_train = vectorizer.fit_transform(news['text'])

In [23]:
start = time.time()
tfidf_tensor = torch.Tensor(tfidf_train.todense())
# print(tfidf_train.size)
# print(tfidf_tensor.size())
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
output = cosine_similarity(tfidf_tensor,tfidf_tensor)

end = time.time()

print(end-start)

ValueError: Expected 2D array, got 1D array instead:
array=[0.         0.         0.         ... 0.01045845 0.01276713 0.        ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [17]:
print(tfidf_tensor[:2])
print(type(tfidf_train))
print(output)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
<class 'scipy.sparse.csr.csr_matrix'>
[[1.0000004  0.04578733 0.01631586 ... 0.10453865 0.02709531 0.04621058]
 [0.04578733 1.0000004  0.0251432  ... 0.06704687 0.02180964 0.11765065]
 [0.01631586 0.0251432  1.0000004  ... 0.05420576 0.08609691 0.02507906]
 ...
 [0.10453865 0.06704687 0.05420576 ... 0.9999998  0.05028451 0.12360325]
 [0.02709531 0.02180964 0.08609691 ... 0.05028451 0.9999999  0.03601346]
 [0.04621058 0.11765065 0.02507906 ... 0.12360325 0.03601346 0.99999964]]


In [25]:
idx = 50
similar = list(enumerate(output[idx]))
similar = sorted(similar, key=lambda x: x[1], reverse=True)
similar = similar[1:6]
movie_index = [i[0] for i in similar]
titles = news['title'].iloc[movie_index]

print(f"News article looking at: {news['title'].iloc[idx]}")
print("Recomendations:")
for text in titles:
    print(text)

News article looking at: American politics has reached peak polarization
Recomendations:
This Is What the Future of American Politics Looks Like
Why swing voters are vanishing from US politics
What's the Answer to Political Polarization in the U.S.?
What divides America? This weekend, it was a Chicago street.
The system set Boehner up for failure
